/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as HomeIndexRouteImport } from "./routes/_home/index";
import { Route as HinoIdRouteImport } from "./routes/hino/$id";

const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/_home/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const HinoIdRoute = HinoIdRouteImport.update({
  id: "/hino/$id",
  path: "/hino/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/hino/$id": typeof HinoIdRoute;
  "/": typeof HomeIndexRoute;
}
export interface FileRoutesByTo {
  "/hino/$id": typeof HinoIdRoute;
  "/": typeof HomeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/hino/$id": typeof HinoIdRoute;
  "/_home/": typeof HomeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/hino/$id" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/hino/$id" | "/";
  id: "__root__" | "/hino/$id" | "/_home/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HinoIdRoute: typeof HinoIdRoute;
  HomeIndexRoute: typeof HomeIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/hino/$id": {
      id: "/hino/$id";
      path: "/hino/$id";
      fullPath: "/hino/$id";
      preLoaderRoute: typeof HinoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  HinoIdRoute: HinoIdRoute,
  HomeIndexRoute: HomeIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
